### ISSUE TITLE
TODO: CWP - Miscellaneous improvements

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/cwp-core#127]
## Description
The following improvements need to be made:
- Rename `CustomHtmlEditorField.php` file to match class name `CustomHtmlEditorFieldToolbar`
- `CwpAtomFeed` - Improve documentation
- `LoginAttemptNotifications` update class description with more details.
- `LoginAttemptNotifications` fix message styles.

**Comment by GuySartorelli** [comment]
Gonna close this. This isn't (technically) a supported module anymore and we won't be doing any more development for it.
