### ISSUE TITLE
TODO: HTMLEditorField_Toolbar is no longer exist in CMS. 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/cwp-core#128]
## Description
HTMLEditorField_Toolbar is no longer exist in CMS. Investigate replacement for HTMLEditorField_Toolbar.
See: https://github.com/silverstripe/cwp-core/blob/db302c9d5c41d74d616fcdfe67367f8f7f0bb391/_config/extensions.yml#L19

**Comment by GuySartorelli** [comment]
Gonna close this. This isn't (technically) a supported module anymore and we won't be doing any more development for it.
