### ISSUE TITLE
Separate out FulltextSearch components to their own repository

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-core#14]
Fulltext functionality is intended to be optional to the site's requirements, however is currently an imposed requirement. While it is not necessary to be _used_, it must be _installed_ in order for a `dev/build` (or any other `flush`ing activity) to succeed.

This issue is of two parts, one to separate out what is contained in this `cwp-core` repository, and the other to affect the `cwp` repository: https://github.com/silverstripe/cwp/issues/21

Ideally there'll be e.g. `cwp/cwp-search` or suchlike that would house the adaptive functionality that enables the features provided by/for the platform, rather than essentially having an unlisted dependency for this module.

**Comment by robbieaverill** [comment]
@tractorcow how do you feel about us moving the fulltextsearch compatibility code from both cwp/cwp-core and cwp/cwp into a new module, e.g. cwp/cwp-search?

**Comment by tractorcow** [comment]
Yes that would be fine. Could you also shift all the basepage code into an extension in that case?

**Comment by robbieaverill** [comment]
Pull requests added to the description of https://github.com/silverstripe/cwp/issues/21
