### ISSUE TITLE
This module should implement a time out on the ProcessJobQueueTask

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-core#3]
**Migrated from GitLab**

cc @jakedaleweb 

This task occasionally hangs which causes jobs not to run. We can implement a time out through here:
https://github.com/silverstripe-australia/silverstripe-queuedjobs/blob/c5ed18700aa7ce20c704f6e996be7d848a273543/src/Services/QueuedJobService.php#L729

10 minutes might be good?

**Comment by robbieaverill** [comment]
We can implement a sensible default. 10 minutes would probably cover most tasks, and users can set a higher timeout if they want to in their project configuration.

Do you want to put up a PR for this change @jakedaleweb?

**Comment by maxime-rainville** [comment]
Looks like this bit of config should take care of this issue for CWP 2. https://github.com/silverstripe/cwp-core/blob/678224ef1d16f09e4bf194a7c93504c8b8dd8c4a/_config/queuedjobs.yml#L12-L13

Feel free to reopen if I'm misreading this
