### ISSUE TITLE
Rename SolrSearchIndex to CwpSolrIndex

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-core#4]
**Migrated from GitLab**

cc @chillu 

See commit message and https://gitlab.cwp.govt.nz/cwp/cwp/merge_requests/65. It's technically an API change, I'm not sure how we handle semver with CWP. Until recently, defining a new index would work in parallel to the built-in CWP index, so its likely that even early adopters of custom indexes won't need to change anything in their custom code.

---

## Comments

_Usernames adjusted for GitHub_

> Damian Mooyman @tractorcow commented 2 years ago

Do you still need this? It'll need a rebase.

> Robbie Averill @robbieaverill commented about a minute ago

I found this very confusing when getting into Solr. +1 for the change. I'll move this to GitHub as an issue and we can attack it for SS4 version.

**Comment by tractorcow** [comment]
This change must be done in a new major version, so pretty much cwp 2.0.0 or 3.0.0.

**Comment by robbieaverill** [comment]
I'm going to make a PR for this change shortly

**Comment by robbieaverill** [comment]
Ok pull request ready to go once #6 is merged in

**Comment by tractorcow** [comment]
Not actually done in https://github.com/silverstripe/cwp-core/pull/6 so re-opening.

**Comment by robbieaverill** [comment]
It was done in #8, not #6

**Comment by tractorcow** [comment]
Doh, you're right.

Have the cwp 2.0 docs been updated with this change?

**Comment by robbieaverill** [comment]
Nah they haven't, but I think we'll need a full task to review all of the docs anyway. I'll make sure we update the cwp/cwp docs in master as we go from now on though

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/cwp/blob/master/docs/en/02_Features/01_Solr_search/04_Default_search_index.md

**Comment by robbieaverill** [comment]
PR coming shortly

**Comment by robbieaverill** [comment]
Ok, pull request at https://github.com/silverstripe/cwp/pull/11
