### ISSUE TITLE
Basic auth on production seems faulty

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cwp-core#67]
The instructions here https://www.cwp.govt.nz/developer-docs/en/2/how_tos/basic_auth/ for enabling basic auth on prod don't appear to be working correctly

```
---
Name: mysitesecuritylive
After: '#cwpsecuritylive'
---
SilverStripe\Security\BasicAuth:
  entire_site_protected: true
```

Non admin users (e.g. content author) were unable to get past the basic auth pop-up after entering their credentials and https://dash.cwp.govt.nz/naut/project/mystack/environment/prod/letmein was not working either

**Comment by robbieaverill** [comment]
I think the "Enabling in production" section is outdated, and needs to be updated to reference BasicAuthMiddleware configuration instead.

**Comment by brynwhyman** [comment]
Raised an issue to update the docs separately https://github.com/silverstripe/cwp/issues/197
