### ISSUE TITLE
RichLinksExtension should not add title attribute to links

### ISSUE THREAD

**Issue by scott1702** [silverstripe/cwp-core#92]
RichLinksExtension adds `title="Open external link"` to any external links. We've had multiple accessibility experts recommend to remove title attributes from links. More information https://developer.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/

**Comment by mark-a-j-adriano** [comment]
#93  -> Attempt to fix the issue

- Remove Title attribute
- Make Unit Test Pass

**Comment by brynwhyman** [comment]
Resolved in https://github.com/silverstripe/cwp-core/pull/93
