### ISSUE TITLE
Solr does not work OOTB with Silverstripe Cloud

### ISSUE THREAD

**Issue by brettt89** [silverstripe/cwp-core#96]
CWP Core recipe defines default CWP configuration for Solr. However this only applies to Revera based hosting. Cloud platforms do not have the same configuration meaning developers are needing to overwrite these settings in order to get Solr to work.

Silverstripe Cloud
- Requires manual implementation of QueuedJobs runner (not included by default now)
- Requires removal of default YML configuration for CWP
E.g. Remove the following from config.yml in project
```
---
Except:
  constantdefined: CWP_ENVIRONMENT
---
CwpSolr:
  options:
    version: 'local-4'
---
Only:
  constantdefined: CWP_ENVIRONMENT
---
CwpSolr:
  options:
    version: 'cwp-4'
---
```
- Requires adding Solr configuraiton to codebase for Silverstripe Cloud - https://servicedesk.silverstripe.cloud/support/solutions/articles/75000012860-solr-search
- Running a Solr_Configure before making the above changes creates a bad index that requires Ops intervention to remove.

All these changes are required currently just to get Solr working with the CWP Recipe on Silverstripe Cloud.

**Comment by brynwhyman** [comment]
> Requires manual implementation of QueuedJobs runner

Hi @brettt89, just double checking what's required here. Are you referring [to this](https://servicedesk.silverstripe.cloud/support/solutions/articles/75000012860-solr-search):

`.platform.yml:`
```
crons:
  queuedjobs_task:
    time: '* * * * *'
    sake_once: "dev/tasks/ProcessJobQueueTask"
    vhost: "mysite"
```

**Comment by brettt89** [comment]
Hi @brynwhyman ,

Yes that is correct, though I don't think that one specifically is an issue with the Recipe (more something we need to call out as needed when running Solr on Platform. So you can probably ignore that part of it - Am discussing it with team at the moment, I had initially copy/pasted this from internal documentation).

**Comment by maxime-rainville** [comment]
Solr is on the way out.
